auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /posts/:year/:month/:day/:title
paginate: 10
category_index: true
category_dir: topics
category_title_prefix: 
exclude: ["lib", "public", "Capfile", "config", "log", "Rakefile", "tmp", ".gitignore", ".git"]
destination: ..\website