auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:title
paginate: 10
category_dir: topics
category_title_prefix: 
exclude: ["lib", "public", "Capfile", "config", "log", "Rakefile", "tmp", ".gitignore", ".git"]
destination: ..\website